name = "ic-1.12.2"
author = "epic_st"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6abd10afe322d65baf7c3cd926d89cdbfdbe919b6b79817278c069c6e37aff2"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
