name = "ic-1.12.2"
author = "epic_st"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "230b073e0fde2123c4a8136a09ddaaf2ac4546e7db318c1449bc735dcacd9f94"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
